import { build } from "esbuild";
import { mkdir, readFile, writeFile } from "node:fs/promises";

const root = new URL("./", import.meta.url);
export async function buildWorkbench(): Promise<string> {
  const bundle = await build({
    absWorkingDir: root.pathname, entryPoints: ["ui/main.tsx"], bundle: true,
    write: false, format: "iife", platform: "browser", target: "es2022", minify: true, charset: "utf8",
    define: { "process.env.NODE_ENV": '"production"' },
  });
  const css = await readFile(new URL("ui/style.css", root), "utf8");
  const script = bundle.outputFiles[0]!.text.replaceAll("</script", "<\\/script");
  return `<!doctype html><html lang="zh"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>AgentEnv</title><style>${css}</style></head><body><div id="root"></div><script>${script}</script></body></html>`;
}

if (import.meta.main) {
  const html = await buildWorkbench();
  await mkdir(new URL("dist/", root), { recursive: true });
  await writeFile(new URL("dist/workbench.ts", root), `// Generated by build-ui.ts.\nexport default ${JSON.stringify(html)};\n`);
}
